// app/layout.tsx
import { ReactNode } from 'react';
import Head from 'next/head';

export const metadata = {
  title: "Pizzaland",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="es">
      <Head>
        {/* Agregar la metaetiqueta viewport aquí */}
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </Head>
      <body>
        {children}
      </body>
    </html>
  );
};

export default Layout;
