import type { Metadata } from "next";
import localFont from "next/font/local";
import Navigation from "./componentes/navigation";
import Header from "./componentes/header";
import "./globals.css";



export const metadata: Metadata = {
  title: "Pizzaland",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
      
        {children}
        
      </body>
    </html>
  );
}